### ISSUE TITLE
SdfMesher free beta?

### ISSUE THREAD

**Issue by enzyme69** [aiekick/SdfMesher_Models#1]
Is there anyway to get access to this SdfMesher tool, I am eager to test it with Blender :) You show some result using MagicaVoxel but how?

If you have article blog or video, I will study~

**Comment by aiekick** [comment]
im preparing the first beta release, for the next month. i will also create some tutorials, and documentation, because its a tool for programmers, not easy to understood i thinck :)

**Comment by brupelo** [comment]
Sdfmesher, really interesting and fun tool... Is there any binary or source to play with? ;)

**Comment by aiekick** [comment]
not for the moment. but he will not be free anymore, i will sell it on steam soon

**Comment by brupelo** [comment]
I see, good luck then, I guess I'll try to code my own algorithm then. Out of curiosity, did you use dual contouring? Any blog or paper you could recommend?

**Comment by aiekick** [comment]
no, i was just inspired by https://github.com/tdhooper/glsl-marching-cubes, the others algo are mine. never understood how to implement dual contouring, for the marching cubes, my code is based on the code found on Paul bourke page : http://paulbourke.net/geometry/polygonise/

**Comment by brupelo** [comment]
Thanks! I'll take a look to it, as far as I know problem with the good old MC was preserving sharp features, isn't? Although there was extended marching cubes as well.. I'm curious, if you tried your technique with these type of [primitives](https://www.shadertoy.com/view/Xds3zN), would you get good results? Said otherwise, is this technique viable for non-blobby meshes?

Anyway, how can we know when/where your tool will be released?

**Comment by aiekick** [comment]
marching cube is the fastest. 

For help a bit for some specific shape, i mesh along a path, by example when i want to meshize my julia revolute shaders (julia fratal along torus). 
by the way there is always problems with sharp edges. but using extended MC or Dual contouring need normal extraction.
So you can't mesh all things (like only picture / buffer) based , 
and use normal is maybe slower. a fast algo is surfaceNet (with normal extraction), not always happy but better in some case, 

i not tried meshing of geometric shapes like your link, the precision come with voxel size. and more triangles and memory uploaded to gpu, but i have created this soft for 3d print, and i prefer smooth fractals :)

i have created others mesher algo, but each have gain or loss. i have not foudn a killer, who have precision and speed. 
if you want see the quality of the models i have obtained with SdfMesher you can go here ( all is free downloadable) https://sketchfab.com/Aiekick

i will share the date and site of the release maybe here, but on my site when he will be finalized, by the way the main source of information is my twitter : https://twitter.com/

i think i will released a demo version with no export possibility and limited generation volume 

my strategy is not fixed at this moment, but i develop this soft since 1.5 year on my free time, and i hope i can gain some money with it :) i have many 50+ functionnality planned to add but i need time :) and time is money :) i hope in a future i will have the possibility to open my code (for the open source community benefits, my code, i use many free mit libs), but its not the moment

**Comment by brupelo** [comment]
Yeah, I've read about surfaces nets few years ago... I'm +/- aware about the main algorithms out there about this topic but I've never tried them in a really cool & useful way like you're doing in sdfmesher :) . Think I'd implemented MC on ~2000 in some glut experiment but that was pretty much so I'm not an expert by any means nowadays.

> but using extended MC or Dual contouring need normal extraction.

Sure, but... is that a problem? Many shadertoys out there will compute normals on these raymarched 1-quad shaders, won't they?

> but i have created this soft for 3d print, and i prefer smooth fractals :)

Nice use case! Having 3d printed mandelbulbs on the desk would be really inspiring lol :)

> i have created others mesher algo, but each have gain or loss. i have not foudn a killer, who have precision and speed.

Well, the fact you can easily switch/test different mesher algos is clever, speaking of which, I'm sure you're aware of existing holes in some cases, right?

![showcase](https://dl.dropboxusercontent.com/s/0jaysqsspfvnou1/chrome_2019-06-20_16-13-53.png)

> my strategy is not fixed at this moment, but i develop this soft since 1.5 year on my free time, and i hope i can gain some money with it :) i have many 50+ functionnality planned to add but i need time :) and time is money :) i hope in a future i will have the possibility to open my code (for the open source community benefits, my code, i use many free mit libs), but its not the moment

I totally understand and I wish you the best of luck with your commercial venture, I'll be tracking some possible news here... in any case, I definitely will try to implement something similar myself when I find the time, I've got my own custom shader/node tools in place so it'd be cool to implement a feature to create/export meshes from shaders.

In any case, if you ever create a blog with relevant implementation details that'd be a really nice reading... for instance, which vertex attributes do you export, pseudocode, etc... ;)

**Comment by aiekick** [comment]
you can check the shader in this directory if you want understand : https://github.com/funparadigm/SdfMesher_Models/tree/master/Larval/Modified_Shader
